### PR TITLE
snap: arch-restrict all steps

### PR DESCRIPTION
**Pull request by xnox**
This should fix FTBFS on non-arm64|amd64.

### CODE REVIEW

**Comment by xnox** [comment]
@jocado somehow the github actions builds are all failing now, and i'm not sure how or why.

They used to work fine.

Also i saw that nvidia stuff got downgraded from 13 releases back to 12, was that intentional or accidental? I cannot tell from the git log.

**Comment by jocado** [comment]
> Also i saw that nvidia stuff got downgraded from 13 releases back to 12, was that intentional or accidental? I cannot tell from the git log.

Apologies - the revert was intentional, but I accidentally added it to another commit it seems.  The build seemed to be failing with that version, and I didn't have to to investigate the cause, so I postponed that version bump until later.

**Comment by xnox** [comment]
> > Also i saw that nvidia stuff got downgraded from 13 releases back to 12, was that intentional or accidental? I cannot tell from the git log.
> 
> Apologies - the revert was intentional, but I accidentally added it to another commit it seems. The build seemed to be failing with that version, and I didn't have to to investigate the cause, so I postponed that version bump until later.

ack, will not bump that yet! i think upstream changed how things are orgnized so it could be related to that.

Separately, trying to figure why the build fails in github ci, but works outside of it.

**Review by jocado — COMMENTED** [review]
@xnox    It looks like we are dropping the requirement for https://github.com/docker-snap/docker-snap/blob/main/patches/libnvidia-container/nvidia-0001-Fix-for-22.04-build.patch , so perhaps rm the patch file too ?

**Comment by jocado** [comment]
> Separately, trying to figure why the build fails in github ci, but works outside of it.

Just having a look now too..

**Comment by jocado** [comment]
Not massively helpful - but I can confirm at least that the build works for me locally too, using the multipass snapcraft provider.

**Comment by xnox** [comment]
@jocado my patches by accident droped `patch.sh` step for libnvidia part, which is what was causing my ci to fail. now fixed i think. So should work here finally.... i hope.....

**Comment by jocado** [comment]
Ahh, thanks @xnox , makes sense, I was just looking at that patch.

I presumed earlier when I saw the PR that you have dropped it on purpose, hence my comment above :) 
https://github.com/docker-snap/docker-snap/pull/131#pullrequestreview-1428321517

**Pull request merged**
